import { useCallback, useEffect, useState } from 'react'
import type { Priority, Recurrence, ReminderRule, Task } from '../types'
import { nextOccurrence } from './recurrence'

const STORAGE_KEY = 'taadaa.tasks'

function loadTasks(): Task[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? (JSON.parse(raw) as Task[]) : []
  } catch {
    return []
  }
}

interface AddTaskInput {
  title: string
  date: string | null
  time?: string | null
  dueDate?: string | null
  projectId?: string | null
  priority?: Priority | null
  tags: string[]
  reminders?: ReminderRule[]
  note?: string | null
  recurrence?: Recurrence | null
  parentId?: string | null
}

export function useTasks() {
  const [tasks, setTasks] = useState<Task[]>(loadTasks)

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(tasks))
  }, [tasks])

  const addTask = useCallback((input: AddTaskInput) => {
    const task: Task = {
      id: crypto.randomUUID(),
      title: input.title,
      date: input.date,
      time: input.time ?? null,
      dueDate: input.dueDate ?? null,
      projectId: input.projectId ?? null,
      priority: input.priority ?? null,
      tags: input.tags,
      reminders: input.reminders ?? [],
      note: input.note ?? null,
      recurrence: input.recurrence ?? null,
      parentId: input.parentId ?? null,
      done: false,
      createdAt: Date.now(),
      order: null,
    }
    setTasks((prev) => [...prev, task])
  }, [])

  const updateTask = useCallback((id: string, changes: Partial<Task>) => {
    setTasks((prev) => prev.map((t) => (t.id === id ? { ...t, ...changes } : t)))
  }, [])

  const restoreTasks = useCallback((restored: Task[]) => {
    setTasks((prev) => [...prev, ...restored])
  }, [])

  /** Wholesale replace, for pulling a synced snapshot from another device. */
  const replaceAllTasks = useCallback((next: Task[]) => {
    setTasks(next)
  }, [])

  // `spawnId`, when given, is used as the id for the next occurrence spawned by
  // completing a recurring task. It's generated by the caller (who can read
  // current `tasks` synchronously) rather than inside the updater below —
  // setState's functional-updater form is only *invoked* later, during
  // reconciliation, not synchronously at the call site, so anything the
  // caller needs to know right away (did this complete the task? what id did
  // the spawned occurrence get?) must be decided before calling this.
  const toggleTask = useCallback((id: string, spawnId?: string) => {
    setTasks((prev) => {
      const task = prev.find((t) => t.id === id)
      if (!task) return prev

      const completing = !task.done
      const updated = prev.map((t) => (t.id === id ? { ...t, done: !t.done } : t))

      if (completing && spawnId && task.recurrence && task.date) {
        const next: Task = {
          ...task,
          id: spawnId,
          done: false,
          date: nextOccurrence(task.date, task.recurrence),
          createdAt: Date.now(),
        }
        return [...updated, next]
      }

      return updated
    })
  }, [])

  const deleteTask = useCallback((id: string) => {
    setTasks((prev) => prev.filter((t) => t.id !== id && t.parentId !== id))
  }, [])

  /** Clears projectId on every task belonging to any of the given projects — used when a project is deleted, so its tasks survive as unfiled rather than vanishing or pointing at a dangling id. */
  const unassignProject = useCallback((projectIds: string[]) => {
    setTasks((prev) =>
      prev.map((t) => (t.projectId && projectIds.includes(t.projectId) ? { ...t, projectId: null } : t)),
    )
  }, [])

  /** Assigns sequential `order` values (0..n-1) to the given task ids, in the order given — drag-reordering within one list writes back the new order this way. Tasks not in `orderedIds` are untouched. */
  const reorderTasks = useCallback((orderedIds: string[]) => {
    setTasks((prev) => {
      const indexOf = new Map(orderedIds.map((id, i) => [id, i]))
      return prev.map((t) => (indexOf.has(t.id) ? { ...t, order: indexOf.get(t.id)! } : t))
    })
  }, [])

  return {
    tasks,
    addTask,
    updateTask,
    toggleTask,
    deleteTask,
    restoreTasks,
    replaceAllTasks,
    unassignProject,
    reorderTasks,
  }
}
